# Generated by Django 6.0.4 on 2026-05-04 13:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("company", models.CharField(blank=True, default="", max_length=120)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("read", "Read"), ("replied", "Replied")],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Enquiry",
                "verbose_name_plural": "Contact Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
