# Generated by Django 6.0.4 on 2026-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_drop_wagtail_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="BJP Technologies (T) Limited", max_length=120)),
                (
                    "tagline",
                    models.CharField(default="Secure Technology. Scalable Growth.", max_length=200),
                ),
                ("email", models.EmailField(default="info@bjptechnologies.co.tz", max_length=254)),
                ("phone", models.CharField(default="+255 678 290 994", max_length=30)),
                (
                    "address",
                    models.CharField(default="Ubungo – Dar es Salaam, Tanzania", max_length=200),
                ),
                (
                    "postal",
                    models.CharField(default="P.O Box 7276, Msakuzi – Mbezi", max_length=100),
                ),
                ("domain", models.CharField(default="bjptechnologies.co.tz", max_length=100)),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("youtube_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
