# Generated by Django 6.0.4 on 2026-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_body",
            field=models.TextField(
                default="BJP Technologies (T) Limited is a full-service IT company headquartered in Ubungo, Dar es Salaam. We build and maintain the software, infrastructure, and security systems that keep growing businesses running — from Tanzanian startups to regional enterprises."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_headline",
            field=models.CharField(
                default="Tanzania's IT Partner Built for East Africa", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_primary",
            field=models.CharField(default="Get Free Consultation", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_cta_secondary",
            field=models.CharField(default="Our Services", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline",
            field=models.CharField(default="Secure Technology. Scalable Growth.", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtext",
            field=models.TextField(
                default="Tanzania's trusted IT partner — delivering tailored software, cybersecurity, cloud, and payment integration solutions that drive real business growth."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_1_label",
            field=models.CharField(default="IT Service Lines", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_1_value",
            field=models.CharField(default="7", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_2_label",
            field=models.CharField(default="Industries Served", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_2_value",
            field=models.CharField(default="6", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_3_label",
            field=models.CharField(default="Monitoring & Support", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_3_value",
            field=models.CharField(default="24/7", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_4_label",
            field=models.CharField(default="Dedicated to Your Success", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="stat_4_value",
            field=models.CharField(default="100%", max_length=20),
        ),
    ]
