# Generated by Django 6.0.4 on 2026-05-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_homepage_content_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutStripSettings",
            fields=[],
            options={
                "verbose_name": "About Strip",
                "verbose_name_plural": "About Strip",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="AddressSettings",
            fields=[],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Address",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="CompanyIdentitySettings",
            fields=[],
            options={
                "verbose_name": "Company Identity",
                "verbose_name_plural": "Company Identity",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="HeroSectionSettings",
            fields=[],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[],
            options={
                "verbose_name": "Social Media Links",
                "verbose_name_plural": "Social Media Links",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="StatsCountersSettings",
            fields=[],
            options={
                "verbose_name": "Stats Counters",
                "verbose_name_plural": "Stats Counters",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
    ]
