# Generated by Django 6.0.4 on 2026-05-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_sitesettings_proxy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageSettings",
            fields=[],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="ContactPageSettings",
            fields=[],
            options={
                "verbose_name": "Contact Page",
                "verbose_name_plural": "Contact Page",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="FooterCTASettings",
            fields=[],
            options={
                "verbose_name": "Footer CTA",
                "verbose_name_plural": "Footer CTA",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="IndustriesPageSettings",
            fields=[],
            options={
                "verbose_name": "Industries Page",
                "verbose_name_plural": "Industries Page",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.CreateModel(
            name="ServicesPageSettings",
            fields=[],
            options={
                "verbose_name": "Services Page",
                "verbose_name_plural": "Services Page",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_banner_headline",
            field=models.CharField(default="Secure Technology. Scalable Growth.", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_intro",
            field=models.TextField(
                default="BJP Technologies (T) Limited is a Tanzanian IT solutions company headquartered in Ubungo, Dar es Salaam. We deliver enterprise-grade technology services — from custom software development and cloud infrastructure to cybersecurity and managed IT — helping businesses across East Africa grow securely and operate at scale."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_our_approach",
            field=models.TextField(
                default="We believe every client deserves solutions tailored to their context — not generic off-the-shelf products. Our team works closely with each organisation to understand their operations, constraints, and goals before recommending or building anything."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_1_label",
            field=models.CharField(default="Projects Delivered", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_1_value",
            field=models.CharField(default="50+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_2_label",
            field=models.CharField(default="Happy Clients", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_2_value",
            field=models.CharField(default="30+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_3_label",
            field=models.CharField(default="Security Audits Done", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_3_value",
            field=models.CharField(default="20+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_4_label",
            field=models.CharField(default="Years in Business", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_stat_4_value",
            field=models.CharField(default="5+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_what_we_do",
            field=models.TextField(
                default="We bring together the technology, expertise, and support businesses need to solve real problems. From secure web applications to cloud infrastructure and mobile money payment integrations — we cover the full technology stack so our clients can focus on growth."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_cta_body",
            field=models.TextField(
                default="Schedule a free consultation with our team. We'll assess your needs and recommend the right technology solutions for your organisation."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_cta_button",
            field=models.CharField(default="Get Free Consultation", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_cta_headline",
            field=models.CharField(default="Ready to Transform Your Business?", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="industries_banner_headline",
            field=models.CharField(default="Tailored Solutions for Every Industry", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="industries_banner_subtext",
            field=models.TextField(
                default="We understand that different sectors have unique technology needs. BJP Technologies delivers solutions built around your industry's specific challenges."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maps_embed_url",
            field=models.CharField(
                default="https://www.google.com/maps?q=-6.750417,39.090111&z=17&output=embed",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_banner_headline",
            field=models.CharField(
                default="Enterprise IT Solutions Built for Tanzania", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_banner_subtext",
            field=models.TextField(
                default="From custom software to cloud infrastructure — we deliver secure, scalable technology that helps businesses across East Africa grow with confidence."
            ),
        ),
    ]
