# Generated by Django 6.0.4 on 2026-05-09 00:20

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_page_content_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoBrandingSettings",
            fields=[],
            options={
                "verbose_name": "Logo & Branding",
                "verbose_name_plural": "Logo & Branding",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sitesettings",),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.FileField(
                blank=True,
                help_text="Accepted: PNG, ICO. Must be square — 32×32 pixels minimum, 64×64 recommended.",
                upload_to="branding/",
                validators=[apps.core.validators.validate_favicon_file],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Accepted: SVG, PNG, WebP. Must have a transparent background. Used in the navbar and footer on dark navy backgrounds.",
                upload_to="branding/",
                validators=[apps.core.validators.validate_logo_file],
            ),
        ),
    ]
