# Generated by Django 6.0.4 on 2026-04-30 12:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "services_offered",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="One relevant service/benefit per line shown on detail page.",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Filename from static/images/industry/ e.g. 01.webp",
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "ordering": ["order", "name"],
            },
        ),
    ]
